### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by alimofar** [adamslab-ub/SCoPP#2]
Do you have any idea about this error?

Traceback (most recent call last):
  File "D:\Users\derw\Desktop\SCoPP-main\demo.py", line 12, in <module>
    way_point_allocator = monitoring_algorithms.QLB(5, environment, plot="full")
  File "D:\Users\derw\Desktop\SCoPP-main\monitoring_algorithms.py", line 64, in __init__
    if len(environment.starting_position) > 1:
AttributeError: 'int' object has no attribute 'starting_position'

**Comment by Collins-IV** [comment]
Issue was with the ordering of parameters in "way_point_allocator = monitoring_algorithms.QLB(5, environment, plot="full")". demo.py has been updated accordingly with the latest commit.

**Comment by alimofar** [comment]
Thanks. I got a new error. Do you have any idea about it?

Traceback (most recent call last):
  File "D:\Users\derw\Desktop\New folder (3)\SCoPP-main\demo.py", line 5, in ?
    import monitoring_algorithms
  File "D:\Users\derw\Desktop\New folder (3)\SCoPP-main\monitoring_algorithms.py", line 712
    with open(self.save_path + "waypoints", 'wb') as f:
            ^
SyntaxError: invalid syntax
