### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by alimofar** [adamslab-ub/SCoPP#3]
I got a new error. Do you have any idea about it?

Traceback (most recent call last):
  File "D:\Users\derw\Desktop\New folder (3)\SCoPP-main\demo.py", line 5, in ?
    import monitoring_algorithms
  File "D:\Users\derw\Desktop\New folder (3)\SCoPP-main\monitoring_algorithms.py", line 712
    with open(self.save_path + "waypoints", 'wb') as f:
            ^
SyntaxError: invalid  #syntax

**Comment by Prajitkk1** [comment]
fixed
