### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by HanHaicheng** [adamslab-ub/SCoPP#4]
Dear Payam,
Python is getting a following error:

Traceback (most recent call last):
  File "C:/Users/admin/Desktop/SCoPP/Swarm_Surveillance/SCoPP/tester.py", line 73, in <module>
    way_points = way_point_allocator.run(info="time")
  File "C:\Users\admin\Desktop\SCoPP\Swarm_Surveillance\SCoPP\monitoring_algorithms.py", line 226, in run
    paths, distances = self.find_optimal_paths(self.planner, robot_assignment_information, waypoints_for_robots)
  File "C:\Users\admin\Desktop\SCoPP\Swarm_Surveillance\SCoPP\monitoring_algorithms.py", line 713, in find_optimal_paths
    with open(self.save_path + "waypoints", 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'MediumLafayetteFlood/waypoints'

May I know how I can solve this?
Thank you.

**Comment by kirito-biter** [comment]
you should build a folder named 'Debug', 'MediumLafayetteFlood', and etc... like this at the source file directory, then build a 'waypoints.txt' file in the folder
